name: platform_info
description: Flutter package of the platform_info plugin.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: platform_info_android
      linux:
        default_package: platform_info_linux

dependencies:
  flutter:
    sdk: flutter
  platform_info_android:
    path: ../platform_info_android
  platform_info_linux:
    path: ../platform_info_linux
  platform_info_platform_interface:
    path: ../platform_info_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.0